apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - github.com/redhat-cop/gitops-catalog/openshift-gitops-operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-operator/overlays/stable?ref=main
    #- github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/overlays/release-2.4?ref=main
  - argocd.yaml

patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-htpasswd-patch.yaml
