kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: operators
spec:
  project: default
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: overlays/cluster-config/operators/
    repoURL: https://github.com/jwennerberg/openshift-gitops-examples.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
