apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jwennerb-infra

#bases:
  #  - ../../../base/sonarqube/
    #  - pipeline/

resources:
  - nexus/argocd-app-nexus.yaml
  - sonarqube/argocd-app-sonarqube.yaml
